[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1Q3uUS0RZH-deTWIAQeOVbJ4AdNH90zQN?usp=sharing)

### NumPy Arrays
- NumPy array are by default Homogeneous, which means data inside an array must be of the same Datatype. 
- NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.


Giới thiệu về NumPy
NumPy (Numerical Python) là một thư viện quan trọng trong Python, được sử dụng rộng rãi trong lĩnh vực khoa học dữ liệu và tính toán khoa học. NumPy cung cấp các công cụ mạnh mẽ để làm việc với mảng (arrays) và ma trận (matrices) đa chiều, cùng với các hàm toán học hiệu quả để thao tác trên các mảng này.

Các tính năng chính của NumPy
Mảng đa chiều (ndarray): NumPy cung cấp một đối tượng mảng n-dimensional array (ndarray) để lưu trữ và thao tác với dữ liệu.
Hiệu suất cao: Các phép toán trên mảng NumPy được thực hiện nhanh chóng và hiệu quả nhờ vào việc sử dụng các thư viện C và Fortran.
Hàm toán học: NumPy cung cấp nhiều hàm toán học để thực hiện các phép toán như cộng, trừ, nhân, chia, và các phép toán phức tạp hơn như đại số tuyến tính, thống kê, và xử lý tín hiệu.
Khả năng tích hợp: NumPy dễ dàng tích hợp với các thư viện khác như SciPy, Matplotlib, Pandas, và nhiều thư viện khác trong hệ sinh thái Python.


In [235]:
import numpy as np
print(np.__version__)

1.26.4


In [236]:
#tạo mảng numpy 

# Tạo mảng 1 chiều
arr1=np.array([1,2,3,4,5])

#tao mang 2 chieu
arr2=np.array([[1,2,3],[4,5,6]])

#tao mang 3 chieu
arr3=np.array([[3,2],[3,4],[1,2]])
print(arr1)
print(arr2)
print(arr3)
# Tạo mảng toàn số 0
zeros_arr = np.zeros((2, 3))
print("Mảng toàn số 0:\n", zeros_arr)

# Tạo mảng toàn số 1
ones_arr = np.ones((2, 3))
print("Mảng toàn số 1:\n", ones_arr)

# Tạo mảng với các giá trị ngẫu nhiên
random_arr = np.random.random((2, 3))
print("Mảng ngẫu nhiên:\n", random_arr)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[3 2]
 [3 4]
 [1 2]]
Mảng toàn số 0:
 [[0. 0. 0.]
 [0. 0. 0.]]
Mảng toàn số 1:
 [[1. 1. 1.]
 [1. 1. 1.]]
Mảng ngẫu nhiên:
 [[0.08120784 0.55365312 0.72319054]
 [0.60974871 0.60691609 0.53567572]]


In [237]:
#Các phép toán trên mảng NumPy:
# Cộng hai mảng
arr_sum = arr1 + arr1
print("Cộng hai mảng:", arr_sum)

# Nhân hai mảng
arr_product = arr1 * arr1
print("Nhân hai mảng:", arr_product)

# Tính tổng các phần tử trong mảng
arr_total = np.sum(arr1)
print("Tổng các phần tử trong mảng:", arr_total)

# Tính trung bình các phần tử trong mảng
arr_mean = np.mean(arr1)
print("Trung bình các phần tử trong mảng:", arr_mean)

Cộng hai mảng: [ 2  4  6  8 10]
Nhân hai mảng: [ 1  4  9 16 25]
Tổng các phần tử trong mảng: 15
Trung bình các phần tử trong mảng: 3.0


In [238]:
# Truy cập phần tử thứ 2 trong mảng 1 chiều
print("Phần tử thứ 2:", arr1[1])

# Truy cập phần tử ở hàng 1, cột 2 trong mảng 2 chiều
print("Phần tử ở hàng 1, cột 2:", arr2[0, 1])

# Cắt mảng 1 chiều từ phần tử thứ 2 đến thứ 4
print("Cắt mảng 1 chiều:", arr1[1:4])

# Cắt mảng 2 chiều: tất cả các hàng, cột 1 và 2
print("Cắt mảng 2 chiều:\n", arr2[:, 1:3])

Phần tử thứ 2: 2
Phần tử ở hàng 1, cột 2: 2
Cắt mảng 1 chiều: [2 3 4]
Cắt mảng 2 chiều:
 [[2 3]
 [5 6]]


In [239]:
np.zeros(3)

array([0., 0., 0.])

In [240]:
type(np.zeros(3))

numpy.ndarray

In [241]:
np.zeros((3))

array([0., 0., 0.])

In [242]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [243]:
#trả về kích thước của mảng đó dưới dạng một tuple
np.zeros(3).shape

(3,)

In [244]:
np.zeros((3,2)).shape

(3, 2)

In [245]:
#trả về số chiều của mảng
np.zeros(3).ndim

1

In [246]:
np.zeros((3,2)).ndim

2

In [247]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [248]:
np.array([[1,2,3,4],[10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [249]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [250]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [251]:
np.linspace(0,4.5,10)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

Cả 

np.random.rand

 và 

np.random.random

 đều được sử dụng để tạo các mảng chứa các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1). Tuy nhiên, chúng có một số khác biệt về cách sử dụng và cú pháp.

### 

np.random.rand



- **Mô tả**: 

np.random.rand

 là một hàm trong module `numpy.random` được sử dụng để tạo các mảng chứa các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1).
- **Cú pháp**: 

np.random.rand(d0, d1, ..., dn)


- **Tham số**: Các tham số `d0, d1, ..., dn` là các kích thước của mảng mà bạn muốn tạo.
- **Trả về**: Một mảng NumPy có kích thước (d0, d1, ..., dn) chứa các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1).

#### Ví dụ:
```python
import numpy as np

# Tạo một mảng 1 chiều với 5 phần tử ngẫu nhiên
arr1 = np.random.rand(5)
print("Mảng 1 chiều với 5 phần tử ngẫu nhiên:", arr1)

# Tạo một mảng 2 chiều với kích thước 3x4
arr2 = np.random.rand(3, 4)
print("Mảng 2 chiều với kích thước 3x4:\n", arr2)
```

### 

np.random.random



- **Mô tả**: 

np.random.random

 là một hàm trong module `numpy.random` được sử dụng để tạo các mảng chứa các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1).
- **Cú pháp**: 

np.random.random(size=None)


- **Tham số**: Tham số `size` là một tuple xác định kích thước của mảng mà bạn muốn tạo. Nếu `size` là `None`, hàm sẽ trả về một giá trị ngẫu nhiên duy nhất.
- **Trả về**: Một mảng NumPy có kích thước `size` chứa các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1).

#### Ví dụ:
```python
import numpy as np

# Tạo một giá trị ngẫu nhiên duy nhất
val = np.random.random()
print("Giá trị ngẫu nhiên duy nhất:", val)

# Tạo một mảng 1 chiều với 5 phần tử ngẫu nhiên
arr1 = np.random.random(5)
print("Mảng 1 chiều với 5 phần tử ngẫu nhiên:", arr1)

# Tạo một mảng 2 chiều với kích thước 3x4
arr2 = np.random.random((3, 4))
print("Mảng 2 chiều với kích thước 3x4:\n", arr2)
```

### So sánh

- **Cú pháp**:
  - 

np.random.rand

 sử dụng các tham số riêng lẻ để xác định kích thước của mảng.
  - 

np.random.random

 sử dụng một tuple để xác định kích thước của mảng.

- **Tính năng**:
  - 

np.random.rand

 chỉ có thể tạo mảng với các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1).
  - 

np.random.random

 cũng tạo mảng với các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1), nhưng có thể trả về một giá trị ngẫu nhiên duy nhất nếu không có tham số `size`.

### Kết luận

Cả 

np.random.rand

 và 

np.random.random

 đều được sử dụng để tạo các mảng chứa các giá trị ngẫu nhiên từ phân phối đều trong khoảng [0, 1). Sự khác biệt chính giữa chúng là cú pháp và cách xác định kích thước của mảng. Việc lựa chọn sử dụng hàm nào phụ thuộc vào sở thích cá nhân và ngữ cảnh cụ thể của bạn.

In [252]:
#
n= 1000000 
a = np.random.rand(n)
b = np.random.rand(n)

In [253]:
import time
import numpy as np

"""
Record multiple running times.
"""
class Timer:
    def __init__(self):
        self.times = []

    def start(self):
        self.tik = time.time()

    def stop(self):
        self.times.append(time.time() - self.tik)
        return self.times[-1]

# Khởi tạo Timer
timer = Timer()

# Khởi tạo các mảng NumPy
n = 1000000
a = np.random.rand(n)
b = np.random.rand(n)

# Đo thời gian cho vòng lặp thủ công
timer.start()
c = np.zeros(n)
for i in range(n):
    c[i] = a[i] + b[i]
timer.stop()

# Đo thời gian cho phép cộng vector hóa
timer.start()
c = a + b
timer.stop()

# In các thời gian đã ghi lại
print("Thời gian chạy:", timer.times)

# Tính toán và in tốc độ tăng tốc
print("Speedup is: %s" % (timer.times[0] / timer.times[1]))

Thời gian chạy: [0.2707819938659668, 0.001071929931640625]
Speedup is: 252.61165480427047


In [254]:
import time 
"""
Record multiple running times.
"""
class Timer: 
    def __init__(self):
        self.times = []

    def start(self):
        self.tik = time.time()
    
    def stop(self):
        self.times.append(time.time() - self.tik)
        return self.times[-1]

In [255]:
timer = Timer()

timer.start()
c = np.zeros(n)
for i in range(n):
    c[i] = a[i] + b[i]
timer.stop()

timer.start()
c = a + b
timer.stop()

0.0010590553283691406

In [256]:
timer.times

[0.3228938579559326, 0.0010590553283691406]

In [257]:
print("speedup is: %s" % (timer.times[0]/timer.times[1]))

speedup is: 304.8885637100405


In [258]:
a = np.array([[1,2,3,4],[10,20,30,40]])
print(a)

[[ 1  2  3  4]
 [10 20 30 40]]


In [259]:
b = a.reshape(4,2)
print(b)

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


In [260]:
b[0,1] = -1

In [261]:
print(b)

[[ 1 -1]
 [ 3  4]
 [10 20]
 [30 40]]


In [262]:
print(a)

[[ 1 -1  3  4]
 [10 20 30 40]]


Dưới đây là giải thích chi tiết về đoạn mã `c > 6` và `c[c > 6]` trong Python với NumPy:

### Giải thích đoạn mã

#### 1. `c > 6`

- **Mô tả**: Biểu thức `c > 6` tạo ra một mảng Boolean có cùng kích thước với mảng `c`, trong đó mỗi phần tử là `True` nếu phần tử tương ứng trong `c` lớn hơn 6, và `False` nếu ngược lại.
- **Ví dụ**:
  ```python
  import numpy as np

  c = np.array([1, 2, 3, 7, 8, 9])
  mask = c > 6
  print(mask)  # Output: [False False False  True  True  True]
  ```

#### 2. `c[c > 6]`

- **Mô tả**: Biểu thức `c[c > 6]` sử dụng mảng Boolean được tạo ra bởi `c > 6` để lọc các phần tử của mảng `c`. Nó chỉ trả về các phần tử của `c` mà tương ứng với giá trị `True` trong mảng Boolean.
- **Ví dụ**:
  ```python
  filtered_c = c[c > 6]
  print(filtered_c)  # Output: [7 8 9]
  ```

### Ví dụ chi tiết

Dưới đây là một ví dụ chi tiết hơn để minh họa cách hoạt động của `c > 6` và `c[c > 6]`:

```python
import numpy as np

# Tạo mảng NumPy
c = np.array([1, 2, 3, 7, 8, 9])

# Tạo mảng Boolean bằng cách so sánh các phần tử của c với 6
mask = c > 6
print("Mảng Boolean (c > 6):", mask)
# Output: [False False False  True  True  True]

# Sử dụng mảng Boolean để lọc các phần tử của c
filtered_c = c[c > 6]
print("Các phần tử của c lớn hơn 6:", filtered_c)
# Output: [7 8 9]
```

### Kết luận

- **`c > 6`**: Tạo ra một mảng Boolean có cùng kích thước với mảng `c`, trong đó mỗi phần tử là `True` nếu phần tử tương ứng trong `c` lớn hơn 6, và `False` nếu ngược lại.
- **`c[c > 6]`**: Sử dụng mảng Boolean được tạo ra bởi `c > 6` để lọc các phần tử của mảng `c`, chỉ trả về các phần tử của `c` mà tương ứng với giá trị `True` trong mảng Boolean.

Việc sử dụng các biểu thức này giúp bạn dễ dàng lọc và thao tác với các phần tử của mảng NumPy dựa trên các điều kiện cụ thể.

In [263]:
c = np.array([3,4,5,6,7,8,9])

In [264]:
c > 6

array([False, False, False, False,  True,  True,  True])

In [265]:
c[c>6]

array([7, 8, 9])