[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1Bf200avbNSsFw4lSbxdgswDStwrkP21p?usp=sharing)

In [1]:
import numpy as np

In [2]:
x = np.array([3,4])

In [3]:
import math 

def vector_norm(vector):
    squares = [elements**2 for elements in vector]
    return math.sqrt(sum(squares))

In [4]:
vector_norm(x)

5.0

In [5]:
from numpy import linalg 
linalg.norm(x)

5.0

### NumPy linear algebra functions
https://numpy.org/doc/stable/reference/routines.linalg.html

In [6]:
y = np.array([2,3])

In [7]:
np.dot(x,y)

18

In [8]:
np.dot(x,y) == np.dot(y,x)

True

In [9]:
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [10]:
x = np.array([2,4,5]).reshape(-1,1)
print(x)

[[2]
 [4]
 [5]]


In [11]:
z = np.matmul(A,x)
print(z)

[[25]
 [58]]


In [12]:
A.shape, x.shape, z.shape

((2, 3), (3, 1), (2, 1))

In [13]:
D = np.array([
            [2, 3, 5, 7],
            [11, 13, 17, 19],
            [23, 29, 31, 37]
])

A = np.array([[3], [4], [5]])

In [14]:
try:
    np.matmul(D, A)
except ValueError as e:
    print("ValueError", e)

ValueError matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)


In [15]:
F = np.array([[5,2],
              [4,1],
              [9,3]])
print(F)

[[5 2]
 [4 1]
 [9 3]]


In [16]:
A = np.array([
        [10, 20, 30],
        [40, 50, 60]
])
print(A)

[[10 20 30]
 [40 50 60]]


In [17]:
A.dot(F)

array([[400, 130],
       [940, 310]])

In [18]:
F.dot(A)

array([[130, 200, 270],
       [ 80, 130, 180],
       [210, 330, 450]])

In [19]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [21]:
E = np.array([[1,1.5], [0,1]])
print(E)

[[1.  1.5]
 [0.  1. ]]


In [22]:
E_inv = linalg.inv(E)
print(E_inv)

[[ 1.  -1.5]
 [ 0.   1. ]]


In [23]:
np.matmul(E, E_inv) 

array([[1., 0.],
       [0., 1.]])

In [24]:
np.matmul(E, E_inv)  == np.eye(2)

array([[ True,  True],
       [ True,  True]])

In [25]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

How to extract all numbers between a given range from a numpy array?


In [26]:
# Get all numbers between 8 and 12
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [27]:
index = np.where(np.logical_and(a >= 8, a <=12))
print(index)

(array([3, 4]),)


In [28]:
a[index]

array([ 9, 10])

In [29]:
c = np.array([1,2,3])

In [30]:
mu, med, sd = np.mean(c), np.median(c), np.std(c)
print(mu, med, sd)

2.0 2.0 0.816496580927726


In [31]:
math.sqrt(sum([(item - mu)**2 for item in c])/3)

0.816496580927726

In [32]:
d = (c - mu)/sd
print(d)

[-1.22474487  0.          1.22474487]


In [33]:
print(np.mean(d), np.std(d))

0.0 0.9999999999999999
