NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [ ]:
# cài đặt numpy nếu chưa cài
#!pip install numpy

In [2]:
import numpy as np #nhập thư viện numpy
#(là thư viện cốt lõi cho tính toán khoa học trong Python. 
#Nó cung cấp một đối tượng mảng đa chiều hiệu suất cao và các công cụ để làm việc với các mảng này.)
print(np.__version__)

1.26.4


In [3]:
a = np.array([1,3,4,5,7,8,9,11])
print(a)
b = a.reshape(2,-1)
print(b)
c = b[:2,1:3]
print(c)

[ 1  3  4  5  7  8  9 11]
[[ 1  3  4  5]
 [ 7  8  9 11]]
[[3 4]
 [8 9]]


In [4]:
sv11 = np.array([1,20,60])
sv12 = np.array([0,20,51])
g1 = np.array([sv11,sv12])
print(g1.shape)

sv21 = np.array([1,22,62])
sv22 = np.array([1,21,41])
g2 = np.array([sv21,sv22])
#print(g2)
class1 = np.array([g1,g2])
print(class1.shape)


(2, 3)
(2, 2, 3)


Mục lục:
1. Tạo mảng (Creating Array)
2. Kích thước khuôn và ép khuôn (Shape and reshape)
3. Chỉ số phần tử trong mảng (Array Indexing)
4. Tách mảng con (Array Slicing) 
5. Sinh giá trị ngẫu nhiên (Randomly generation of values)
6. Tính toán trên ma trận (Operations on matrices)

In [5]:
import numpy as np
# 1. creating array
# one dimension
arr = np.array([1,3,5,7])
print('one dim:\n',arr)
print(list(arr))

# two dimensions 
arr = np.array([[1,3,5],
                [2,4,6]])
print('two dim:\n',arr)
# three dimensions: it means array of 2-dim arrays 
arr = np.array( [ [[1,3,5],[2,4,6]],
                     [[10,30,50],[20,40,60]] 
                    ]   )
print('three dim:\n',arr)

one dim:
 [1 3 5 7]
[1, 3, 5, 7]
two dim:
 [[1 3 5]
 [2 4 6]]
three dim:
 [[[ 1  3  5]
  [ 2  4  6]]

 [[10 30 50]
  [20 40 60]]]


In [6]:
# convert from list to numpy array 
a = [1,2,3]
print(a) 
arr = np.array(a)
print(arr)

[1, 2, 3]
[1 2 3]


In [7]:
a = np.arange(10)
print(a)
a = np.arange(2,10)
print(a)
a = np.arange(1,10,2)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [8]:
a = np.random.rand(2,3)
print(a)
b = np.random.randint(10,size=(2,5))
print(b)
c = np.random.rand(15)*10
print(c)

[[0.98173777 0.27273211 0.94911123]
 [0.73113149 0.14031811 0.01186404]]
[[5 2 6 0 8]
 [2 7 6 5 6]]
[9.21774711 9.33325298 4.93858106 1.2201462  3.21400998 3.99908021
 7.98594911 8.30970516 7.11072207 3.4946508  4.77120764 1.31157525
 8.38279573 8.20015812 2.0582464 ]


In [9]:
a = np.random.rand(3,4)*4+15
print(a)

[[15.87395365 18.81733055 17.17282222 18.57285378]
 [17.30747463 16.49799036 17.72572024 18.13021353]
 [15.70025902 18.34051642 16.8901894  16.78678571]]


In [10]:
a = np.random.rand(3,5)*5 + 10
print(a)

[[11.63663658 13.43942857 11.95777032 14.19000699 14.91120858]
 [14.47881747 11.47756654 11.28698428 11.42110519 10.69318291]
 [12.42992845 10.23322047 12.08187273 13.74250308 11.31547972]]


In [11]:
#a = np.random.randint(10,size=(3, 7))
print('a=\n',a)
b = a[ -2: , -3: ]
print('b=\n',b)


a=
 [[11.63663658 13.43942857 11.95777032 14.19000699 14.91120858]
 [14.47881747 11.47756654 11.28698428 11.42110519 10.69318291]
 [12.42992845 10.23322047 12.08187273 13.74250308 11.31547972]]
b=
 [[11.28698428 11.42110519 10.69318291]
 [12.08187273 13.74250308 11.31547972]]


In [12]:
#a = np.random.rand(2,3)*10+10
height = np.random.rand(10)*0.3+1.5
print(height)
weight = height*30
eps = np.random.rand(10)*3
weight = weight+eps
print(weight)
x = 1.61
y = 1

SyntaxError: invalid syntax (3381326951.py, line 9)

In [34]:
# - array with the same value
a = np.full((2,3),4.5)
print(a)
a = np.full((5),2)
print(a)
# create array by multiple 
a = np.array([2]*5)
print(a)

# random values

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(2,3) # array (2,3) with values in [0,1]
print(a) 
a = np.random.rand(3) 
print(a) 
a = np.random.rand(3,2,4) 
print(a) 
# randint for values of integers 
a = np.random.randint(10,size=5) # values in [0,10]
print(a)
a = np.random.randint(10,size=(2,5))
print(a)

[[4.5 4.5 4.5]
 [4.5 4.5 4.5]]
[2 2 2 2 2]
[[0.01888834 0.23105233 0.73590319]
 [0.42249653 0.63996952 0.17457706]]
[0.12513783 0.33886594 0.15180212]
[[[0.83701196 0.64058348 0.55261312 0.73110596]
  [0.52162478 0.13127607 0.61851923 0.4318031 ]]

 [[0.75709295 0.26777998 0.98420076 0.91613044]
  [0.65189709 0.33628074 0.8807207  0.43254357]]

 [[0.92162656 0.79654823 0.38310808 0.37098824]
  [0.8303153  0.01445566 0.53472576 0.37626156]]]
[0 9 6 3 8]
[[1 8 9 2 5]
 [7 3 4 5 8]]


In [67]:
#a = np.random.randint(10,size=(4,6))
print(a)
X=a[:,:-1]
y=a[:,-1]
print('X=',X)
print('y=',y)
#print(b)

[[8 3 6 7 8 8]
 [1 3 0 2 6 8]
 [0 2 7 3 0 7]
 [0 8 6 6 7 1]]
X= [[8 3 6 7 8]
 [1 3 0 2 6]
 [0 2 7 3 0]
 [0 8 6 6 7]]
y= [8 8 7 1]


In [8]:
a=np.random.randint(10,size=24)
print(a)
b = a.reshape(4,-1)
print(b.shape)
print(b)
c = b.reshape(2,3,-1)
print(c.shape)
print(c)


[3 0 6 9 1 4 2 4 1 2 1 8 3 6 2 4 9 5 2 8 5 0 2 2]
(4, 6)
[[3 0 6 9 1 4]
 [2 4 1 2 1 8]
 [3 6 2 4 9 5]
 [2 8 5 0 2 2]]
(2, 3, 4)
[[[3 0 6 9]
  [1 4 2 4]
  [1 2 1 8]]

 [[3 6 2 4]
  [9 5 2 8]
  [5 0 2 2]]]


In [24]:
#a = np.random.randint(10,size=(12))
a = a.reshape(3,4)
print(a)
b = a[-2:,-2:]
print(b)
#print(a.shape)


[[2 7 6 9]
 [4 1 5 7]
 [0 6 0 6]]
[[5 7]
 [0 6]]


In [28]:
a = np.random.randint(20,size=20)
print(a)
a = a.reshape(4,-1)
print(a)
#b = a[1:3,1:4]
#print('b=',b)



[13 12 11 18 12  5  2  3 12  0  8  8  8 10 19  8 14 10 18 10]
[[13 12 11 18 12]
 [ 5  2  3 12  0]
 [ 8  8  8 10 19]
 [ 8 14 10 18 10]]


In [37]:
a = np.arange(1,31)
a = a.reshape(30,-1)
#print(a)
#b = np.random.randint(3,10,size=(30,3))
#print(b)
c = np.concatenate((a,b),axis=-1)

print(c)

[[ 1  6  6  4]
 [ 2  4  3  3]
 [ 3  6  4  6]
 [ 4  3  6  9]
 [ 5  7  4  7]
 [ 6  9  7  8]
 [ 7  8  5  4]
 [ 8  5  4  4]
 [ 9  5  5  8]
 [10  8  4  3]
 [11  7  4  7]
 [12  4  3  7]
 [13  8  6  7]
 [14  3  9  6]
 [15  5  5  8]
 [16  7  4  7]
 [17  8  5  4]
 [18  3  9  6]
 [19  4  5  9]
 [20  5  4  6]
 [21  4  3  6]
 [22  8  6  7]
 [23  5  8  6]
 [24  5  7  7]
 [25  3  6  4]
 [26  9  6  8]
 [27  4  4  3]
 [28  6  9  6]
 [29  6  8  4]
 [30  8  7  9]]


In [122]:
import random 
n = random.randint(10,20)
print(n)
a = [random.randint(10,20) for i in range(5) ]
print(a)
b = np.array(a)
print(b) 

10
[13, 20, 13, 13, 11]
[13 20 13 13 11]


In [121]:
# 2. shape and reshape 
a = np.array([[1,3,5,7],
                [2,4,6,8],[1,1,1,1]])
print(a.shape)
print(a.shape[0],a.shape[1])
# reshape to (m,n)
print(np.reshape(a,(2,6)))
print(a.reshape(2,6))
print(a.reshape(2,-1))

# reshape to one line
print(a.ravel())
print(a.reshape(-1,6))
print(a.reshape(6,-1))

(3, 4)
3 4
[[1 3 5 7 2 4]
 [6 8 1 1 1 1]]
[[1 3 5 7 2 4]
 [6 8 1 1 1 1]]
[[1 3 5 7 2 4]
 [6 8 1 1 1 1]]
[1 3 5 7 2 4 6 8 1 1 1 1]
[[1 3 5 7 2 4]
 [6 8 1 1 1 1]]
[[1 3]
 [5 7]
 [2 4]
 [6 8]
 [1 1]
 [1 1]]


In [50]:
# 2,3. array indexing and slicing 
# how to get/extract values by indexs in arrays
a = np.array([1,3,5,7])
for i in range(len(a)):
    print(a[i], end=' ')
b = np.array([[1,3,5],[2,4,6]])
print('\n\rshape =',b.shape)
print(b)
for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        print(b[i][j])

1 3 5 7 
shape = (2, 3)
[[1 3 5]
 [2 4 6]]
1
3
5
2
4
6


In [55]:
# how to get sub-array by indexs
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[:3])
print(a[1:3])
print(a[-1])
print(a[3:-1])
print(a[:-1])


[1 2 3]
[2 3]
9
[4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [61]:
# how to get sub-array of 2-dim arrays by indexs
a = np.array([[1,3,5],[2,4,6]])
print(a)
print(a[0:2,1:3])
print(a[:,:-1])
print(a[:,:])

[[1 3 5]
 [2 4 6]]
[[3 5]
 [4 6]]
[[1 3]
 [2 4]]
[[1 3 5]
 [2 4 6]]


In [71]:
#4. Array extraction by Condition
a = np.array([i for i in range(10)])
print(a)
# get odd values
b = a[a%2==1]
print(b)


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [75]:
# 5. Data type
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

<U6
int64


In [87]:
# 6. Operation on darray
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[1,1,1],[2,2,2]])
print(a)
print(b)

[[1 2 3]
 [2 3 4]]
[[1 1 1]
 [2 2 2]]


In [95]:
print(a+b)
print('add',np.add(a,b))
print(a-b)
print('sub',np.subtract(a,b))
print(a*b)
print('multiply',np.multiply(a,b))
print(a/b)
print('divide',np.divide(a,b))

[[2 3 4]
 [4 5 6]]
add [[2 3 4]
 [4 5 6]]
[[0 1 2]
 [0 1 2]]
sub [[0 1 2]
 [0 1 2]]
[[1 2 3]
 [4 6 8]]
multiply [[1 2 3]
 [4 6 8]]
[[1.  2.  3. ]
 [1.  1.5 2. ]]
divide [[1.  2.  3. ]
 [1.  1.5 2. ]]


In [98]:
print(a)
print(b.T) # Transpose of a matrix (ma trận chuyển vị))
print(np.dot(a,b.T))
print(np.sqrt(a))

[[1 2 3]
 [2 3 4]]
[[1 2]
 [1 2]
 [1 2]]
[[ 6 12]
 [ 9 18]]
[[1.         1.41421356 1.73205081]
 [1.41421356 1.73205081 2.        ]]


In [108]:
# operation by axis of array
print(a)
print(b)
# operation on by axis
print(a.sum(axis=0))
print(a.sum(axis=1))
# combine a and b: numpy.concatenate 
print('concat:')
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[1 2 3]
 [2 3 4]]
[[1 1 1]
 [2 2 2]]
[3 5 7]
[6 9]
concat:
[[1 2 3]
 [2 3 4]
 [1 1 1]
 [2 2 2]]
[[1 2 3 1 1 1]
 [2 3 4 2 2 2]]


In [20]:
# Create a 2x7 matrix
# line 1 is random integers from 10->20
# line 2 is real numbers from 10 ->20
#2) get/extract sub-matrix from column 2 to column 4 
#and print to screen











N = 5
a = np.random.rand(N)*10+10
print(a)
b = np.random.randint(10,20, size=(N))
print(b)
c = np.array([b,a])
print(c)
d = c[:,2:4]
print(d)

[18.50006698 10.8865592  17.79527301 12.84290472 13.96935492]
[16 13 12 19 18]
[[16.         13.         12.         19.         18.        ]
 [18.50006698 10.8865592  17.79527301 12.84290472 13.96935492]]
[[12.         19.        ]
 [17.79527301 12.84290472]]


In [69]:
a = np.array([1,2,3])
b = np.array([2,2,1])
c = a*b
print(c)

[2 4 3]
